# This file specifies the JVM version to be used for the Gradle Daemon.
# We only pin the version to ensure consistency across environments.
# The Foojay plugin in settings.gradle.kts handles the download if Java 21 is missing.
toolchainVersion=21